rewrote approach to backups

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,88 +1,52 @@
 #!/bin/bash
 #
-# pbrisbin 2009, 2010
+# pbrisbin 2010
 #
-# example config file contents
-#
-#  # where to log output
-#  LOG='/home/patrick/.logs/backup.log'
-#  
-#  # where to store daily backups
-#  BACKUP_DAILY='/mnt/backup/daily'
-#  
-#  # where to store monthly backups
-#  BACKUP_MONTHLY='/mnt/backup/monthly'
-#  
-#  # a file containing rsync exclude patterns
-#  EXCLUDES='/home/patrick/.backups/backup_exclude.lst'
-#  
-#  # an array of folders to be backed up
-#  INCLUDES=( '/home/patrick' '/etc' '/usr' '/var' '/boot' )
+# rewritten based on ideas from falconindy's SquashFu:
+#       http://github.com/falconindy/SquashFu
 #
 ###
 
-message()  { echo 'usage: backup [ -v ] [ -d | -m ]'; exit 1; }
-logger()   { echo "$(date +'[ %d %b %Y %H:%M ]') :: $*" | tee -a "$LOG"; }
-errorout() { logger "error: $*"; exit 1; }
+message()  { echo 'usage: backup [ -d | -m | --media ]'; exit 1; }
+errorout() { echo "error: $*" >&2; exit 1; }
 
-# backup a single directory
-backup_dir() {
-  local ret=0 folder
+# normal backup settings
+backup_daily='/mnt/backup/daily'
+backup_monthly='/mnt/backup/monthly'
 
-  for folder in "$@"; do
-    $verbose && logger "  ...$folder"
+includes=(/srv/http /home/patrick /etc /usr /var /boot)
+excludes=(Downloads lost+found)
 
-    if [[ "$folder" = '/home/patrick' ]]; then
-      # note - i handle my ~/ specially
-      rsync -a -l --delete \
-                  --delete-excluded \
-                  --exclude-from="$excludes" \
-                  "$folder" "$dir/" &>> "$LOG" || ret=1
-    else
-      # all other dirs
-      rsync -a -l --delete "$folder" "$dir/" &>> "$LOG" || ret=1
-    fi
-  done
+# my large media collection is handled specially
+backup_media='/mnt/backup2'
+media_includes=(/mnt/data1/Rips /mnt/data2/Movies /mnt/data2/TV_shows)
+media_excludes=(converted)
 
-  return $ret
-}
+if [[ "$1" = '--media' ]]; then
+  # do a media compression and exit
+  echo "compressing media to $backup_media/media.tbz2"
+  tar cpjf "$backup_media/media.tbz2" ${media_excludes[@]/#/--exclude } "${media_includes[@]}"
+  exit $?
+fi
 
-# set defaults
-conf='/home/patrick/.config/backup.conf'
-verbose=false
+case "$1" in
+  -d|--daily)   backup_dir="$backup_daily"   ;;
+  -m|--monthly) backup_dir="$backup_monthly" ;;
+  *)            message                      ;;
+esac
 
-# inital sanity checks
-[[ -n "$1"        ]] || message
-[[ $(id -u) -eq 0 ]] || errorout 'you must be root'
-[[ -f "$conf"     ]] || errorout 'config file not found'
-# source config
-. "$conf"
+# default
+backup_dir="${backup_dir:-$backup_daily}"
 
-# set excludes variable
-excludes="$EXCLUDES"
+# initial checks
+[[ $(id -u) -eq 0         ]] || errorout 'only root can do that...'
+[[ -f "$backup_dir/.lock" ]] || errorout "$backup_dir/.lock not found, is it mounted?"
 
-# gather other options
-while [[ -n "$1" ]]; do
-  case $1 in
-    -d) dir="$BACKUP_DAILY"   ;;
-    -m) dir="$BACKUP_MONTHLY" ;;
-    -v) verbose=true          ;;
-    *)  message               ;;
-  esac
-  shift
-done
+echo "syncing directories to $backup_dir/"
+rsync -a -l --delete --delete-excluded "${includes[@]}" ${excludes[@]/#/--exclude } "$backup_dir/"
 
-# additional sanity checks
-[[ -f "$excludes"  ]] || errorout 'excludes file not found'
-[[ -n "$dir"       ]] || errorout 'backup directory not set'
-[[ -f "$dir/.lock" ]] || errorout 'backup directories not mounted'
+echo 'generating package lists...'
+pacman -Qqe | grep -Fvx "$(pacman -Qqm)" > "$backup_dir/paclog" || errorout 'failed creating paclisting'
+pacman -Qqm > "$backup_dir/aurlog"                              || errorout 'failed creating aur listing'
 
-$verbose && logger 'backing up directories...'
-backup_dir ${INCLUDES[@]} || errorout 'failed to backup directories'
-
-$verbose && logger 'generating package lists...'
-pacman -Qqe | grep -Fvx "$(pacman -Qqm)" > "$dir/paclog" || errorout 'failed creating paclisting'
-pacman -Qqm > "$dir/aurlog"                              || errorout 'failed creating aur listing'
-
-$verbose && logger 'done'
-exit 0
+echo 'done'
