checkip: remove loggin, user read

diff --git a/checkip b/checkip
--- a/checkip
+++ b/checkip
@@ -4,14 +4,12 @@
 #
 ###
 
-logger() { echo "$(date +'[ %d %b %Y %H:%M ]') $*" | tee -a "$log"; }
-
-errorout() { logger "error: $*"; exit 1; }
+errorout() { echo "error: $*" >&2; exit 1; }
 
 update_dns() {
   local file="$HOME/.credentials"
 
-  logger "ip changed: $old -> $new"
+  echo "ip changed: $old -> $new"
 
   # read user/pass from cred file
   [[ -f "$file" ]] && . "$file" || errorout 'dns not updated, credentials file not found'
@@ -21,17 +19,14 @@ update_dns() {
 
   # store new ip
   echo $new > "$ipfile"
-  logger 'dns updated. the change may take up to an hour to be seen.'
+  echo 'dns updated. the change may take up to an hour to be seen.'
 }
 
-log="${LOGS:-$PWD}/checkip.log"
-
-ip_url='http://tnx.nl/ip'
 ipfile="$HOME/.myip"
 
 touch "$ipfile"
 
 read -r old < "$ipfile"
-new="$(wget -q -O - "$ip_url")"
+read -r new < <(wget -q -O - 'http://tnx.nl/ip')
 
 [[ "$old" != "$new" ]] && update_dns || exit 0
