goodsong: full rewrite, unreadable diff

diff --git a/goodsong b/goodsong
--- a/goodsong
+++ b/goodsong
@@ -1,160 +1,115 @@
 #!/bin/bash
 #
-# goodsong: maintain a list of favourite songs.
+# goodsong: maintain a list of good songs.
 #
-# pbrisbin 2009, 2010
+# pbrisbin 2009, 2010, 2011
 #
-# Contributors:
+# requires playlist_directory and music_directory be set in mpd.conf
+#
+# contributors:
 #   Tom Vincent <http://www.tlvince.com/contact/>
 #   Christian
 #
 ###
 
-errorout() { echo "$*" >&2; exit 1; }
+errorout() { echo "error: $*" >&2; exit 1; }
 
 message() {
   cat << EOF
-usage: goodsong [option]
+  usage: goodsong [ -p | -ls ]
 
-  options:
+    options:
+          -p,--play   play a random good song
+          -ls,--list  print your list with music dir prepended
 
-        -p, --play        play a random song from list, now
-
-        -b, --build       build a playlist from your list, play it
-
-        -s, --show        display a random song from list
-
-        -f, --find regex  find a song in your list using grep 'regex'
-
-        -S, --smart       select a song from your list; find it in
-                          your current playlist or add it; when the
-                          current song ends, play it
-
-        -P, --print       print your list with music dir prepended
-
-        -h, --help        display this
-
-        none              append playing song to list
+          none        note the currently playing song as good
 
 EOF
+  exit 1
 }
 
-# Return the mpd.conf passed as a parameter to mpd or an expected default
-locateMPDConf() {
-  # Don't use any command that overrides the "real" mpd binary
-  local config="$(pgrep -fl $(which --skip-tilde mpd)\  | awk '{print $3}')"
+mpd_prop() {
+  local value
 
-  if [[ -z $config ]]; then
-    if [[ -r "$HOME/.mpd/mpd.conf" ]]; then
-      config="$HOME/.mpd/mpd.conf"
-    elif [[ -r '/etc/mpd.conf' ]]; then
-      config='/etc/mpd.conf'
-    else
-      errorout "unable to locate a readable mpd.conf"
-    fi
+  # note: error handling left to caller
+  read -r value < <(sed -r '/^'"$1"' *(\"|'\''|)([^\1]*)\1/!d; s//\2/g' "$mpd_config")
+  echo "${value/\~/$HOME}"
+}
+
+# todo: add --config option
+set_config() {
+  unset mpd_config
+  
+  # mpd.conf passed on commandline
+  read -r mpd_config < <(pgrep -fl $(which --skip-tilde mpd)\  | awk '{print $3}')
+  [[ -n "$mpd_config" ]] && return 0
+
+  mpd_config="$HOME/.mpd/mpd.conf"
+  [[ -n "$mpd_config" ]] && return 0
+
+  mpd_config='/etc/mpd.conf'
+  [[ -n "$mpd_config" ]] && return 0
+
+  return 1
+}
+
+# todo: add --playlist option
+set_playlist() {
+  unset playlist_file
+  local playlist_directory
+
+  read -r playlist_directory < <(mpd_prop 'playlist_directory')
+  [[ -z "$playlist_directory" ]] && return 1
+
+  # return exit status from touch call
+  playlist_file="$playlist_directory/goodsongs.m3u"
+  touch "$playlist_file" &>/dev/null
+}
+
+play_random() {
+  local track position
+  
+  read -r track < <(sort -R "$playlist_file")
+  [[ -z "$track" ]] && return 1
+
+  # look for it in current playlist
+  read -r position < <(mpc --format '%position% %file%' playlist |\
+    awk "/[0-9]* ${track//\//\\/}$/"'{print $1}')
+
+  if [[ -z "$position" ]]; then
+    mpc -q add "$track" # add it
+    read -r position <(mpc playlist | wc -l)
   fi
 
-  echo "$config"
+  [[ -n "$position" ]] && mpc -q play "$position"
+
+  exit $? # non-zero on empty var or mpc error
 }
 
-# From the given property key ($1), lookup the value in the given ini file ($2),
-# where value can be single, double, or un-quoted.
-confParser() {
-    sed -r '/^'"$1"' *(\"|'\''|)([^\1]*)\1/!d; s//\2/g' "$2"
+print_list() {
+  local music_directory
+  
+  read -r music_directory < <(mpd_prop 'music_directory')
+  [[ -n "$music_directory" ]] && sed "s|^|$music_directory/|g" "$playlist_file"
+
+  exit $? # non-zero on empty var or sed error
 }
 
-# From the given regex ($1), find the relevant mpd.conf property value
-mpdParam() {
-  local param="$(confParser "$1" "$(locateMPDConf)")"
-  [[ -z $param ]] && errorout "'$1' is an invalid mpd.conf property key"
-  echo "${param/\~/$HOME}"   # translate '~' to '$HOME'
-}
+which mpc &>/dev/null || errorout 'mpc binary required'
+set_config            || errorout 'unable to locate mpd config file'
+set_playlist          || errorout 'unable to access a playlist file'
 
-# just prints your list with the music dir prepended (for easy piping, etc)
-printlist() {
-  local mdir="$(mpdParam '^music_directory')"
-  sed "s|^|$mdir/|g" "$list"
-}
-
-# return playlist position of a random good song
-get_pos() {
-  local track="$(cat $list | sort -R | head -n 1)" pos
-
-  pos=$(mpc --format '%position% %file%' playlist | \
-        awk "/[0-9]* ${track//\//\\/}$/"'{print $1}' | head -n 1)
-
-  if [[ -z "$pos" ]]; then
-    mpc add "$track"
-    pos=$(mpc playlist | wc -l)
-  fi
-
-  echo "$pos"
-}
-
-# returns current seconds remaining
-get_lag() {
-  local time curm curs totm tots lag n
-
-  IFS=':/' read curm curs totm tots < <(mpc | awk '/playing/ { print $3 }')
-
-  if [[ -z "$curm$curs$totm$tots" ]]; then
-    lag=0 # blanks means stopped
-  else
-    cur=$((curm*60+curs))
-    tot=$((totm*60+tots))
-    lag=$((tot-cur))
-
-    # adjust lag based on crossfade
-    read n < <(mpc crossfade | awk '{ print $2 }')
-    [[ -n "$n" ]] && lag=$((lag-n))
-  fi
-
-  echo "$lag"
-}
-
-# build a playlist and play it
-build_playlist() { mpc load goodsongs; mpc play; }
-
-# add current song to the list
-add_to_list() {
-  # is mpd playing?
-  mpc | grep -Fq playing || exit 1
-
-  # get song filename
-  read song < <(mpc --format %file% | head -n 1)
-
-  # add it -- prevent dupes
-  grep -Fqx "$song" "$list" || echo "$song" >> "$list"
-}
-
-# queue up a good song for when the current song ends
-smart_play() { (sleep $(get_lag) && mpc play $(get_pos) &>/dev/null) & }
-
-# show one random good song
-show_one() { shuf -n1 "$list"; }
-
-# play a random good song
-play_one() { mpc play $(get_pos); }
-
-# search the list
-search_list() { grep -i "$*" "$list"; }
-
-parse_options() {
+if [[ -n "$1" ]]; then
   case "$1" in
-    -h|--help)  message && exit 1       ;;
-    -s|--show)  show_one                ;;
-    -f|--find)  shift; search_list "$*" ;;
-    -p|--play)  play_one                ;;
-    -b|--build) build_playlist          ;;
-    -S|--smart) smart_play              ;;
-    -P|--print) printlist               ;;
-    *)          add_to_list             ;;
+    -p|--play)  play_random ;;
+    -ls|--list) print_list  ;;
+    *)          message     ;;
   esac
-}
+fi
 
-list="$(mpdParam 'playlist_directory')/goodsongs.m3u"
-touch "$list" &>/dev/null || errorout 'unable to write playlist file'
+# default action, note song as good
+read -r song < <(mpc --format %file%)
+[[ -n "$song" ]] && \
+  { grep -Fqx "$song" "$playlist_file" || echo "$song" >> "$playlist_file"; }
 
-parse_options "$@"
-
-# vim: set ts=2 sw=2 :
+exit $? # non-zero on empty var or echo error
