leave: full rewrite

diff --git a/leave b/leave
--- a/leave
+++ b/leave
@@ -1,43 +1,60 @@
 #!/bin/bash
 #
-# a simple logout dialog
+# leave - pbrisbin 2011
+#
+# a simple shut-down dialog implemented via dmenu
+# 
+# note: requires NOPASWD entries for the commands involved (when not
+# using --no-sudo).
+#
+# todo:
+#       remove duplicate code re: --no-sudo
+#       verify bash version supports assoc arrays
 #
 ###
 
-kill_apps() {
-  while read -r app; do
-    wmctrl -i -c "$app"
-  done < <(wmctrl -l | awk '{print $1}')
-}
+errorout() { echo "error: $*"                 ; exit 1; }
+message()  { echo 'usage: leave [ --no-sudo ]'; exit 1; }
 
-choice_by_zenity() {
-  choice=$(zenity --title="Logout $HOSTNAME" \
-                  --text="Logout $HOSTNAME:" \
-                  --list --radiolist \
-                  --hide-column=3 --print-column=3 \
-                  --column='' --column='' --column='' \
-                  TRUE Logout 0 FALSE Reboot 1 FALSE Shutdown 2)
-}
+have() { which $1 &>/dev/null }
 
-choice_by_dmenu() {
-  local dmenu="dmenu ${DMENU_OPTS:--i}"
+[[ "$1" =~ -h|--help ]] && message
 
-  choice="$(echo -e "0: Logout\n1: Reboot\n2: Shutdown" | $dmenu | cut -d ':' -f 1)"
-}
+declare -A choices
 
-[[ -z "$DISPLAY" ]] && exit 1
+choices[logout]='pkill X'
 
-#choice_by_zenity
-choice_by_dmenu
+if [[ "$1" == '--no-sudo' ]]; then
+  choices[shutdown]='shutdown -h now'
+  choices[reboot]='shutdown -r now'
 
-[[ -z "$choice" ]] && exit 1
+  if have pm-suspend; then
+    choices[suspend]='pm-suspend'
+  else
+    choices[suspend]='echo -n mem >/sys/power/state'
+  fi
 
-# gracefully close all open apps
-kill_apps
+  have pm-hibernate && choices[hibernate]='pm-hibernate'
+else
+  have sudo || errorout 'no sudo binary found'
 
-# execute the choice in background
-case "$choice" in
-  0) pkill X &              ;;
-  1) sudo shutdown -r now & ;;
-  2) sudo shutdown -h now & ;;
-esac
+  choices[shutdown]='sudo shutdown -h now'
+  choices[reboot]='sudo shutdown -r now'
+
+  if have pm-suspend; then
+    choices[suspend]='sudo pm-suspend'
+  else
+    choices[suspend]='sudo /bin/sh -c "echo -n mem >/sys/power/state"'
+  fi
+
+  have pm-hibernate && choices[hibernate]='pm-hibernate'
+fi
+
+dmenu="dmenu ${DMENU_OPTS:--i}"
+
+choice="$(printf "%s\n" "${!choices[@]}" | $dmenu)" 
+
+if [[ -n "$choice"]]; then
+  action="${choices[$choice]}"
+  [[ -n "$action"]] && $action
+fi
