synergize: small fixes

diff --git a/synergize b/synergize
--- a/synergize
+++ b/synergize
@@ -19,42 +19,42 @@ message() {
   echo "  if present, the server is immediately initialized for [host]"
   echo
   echo "  else, the server is initialized for the first host found"
-  echo "  in the array \$HOSTS that answers ping"
+  echo "  in the array \$hosts that answers ping"
   echo
   exit 1
 }
 
 logger() { echo "$(date +'[ %m %b %Y %H:%M ]') :: $*" | tee -a "$log"; }
 
-errorout() { logger "error: $*"; exit 1; }
+errorout() { logger "error: $*" >&2; exit 1; }
 
 connect() {
   pid=$(pgrep synergy)
-  cur=$(awk '/^#SETUPFOR/ {print $2}' $file)
+  cur="$(awk '/^#SETUPFOR/ {print $2}' "$file")"
 
   [[ -z "$cur" ]] && errorout 'cannot determine current host'
 
-  if [ "$cur" = "$1" ]; then 
-    logger "prepared for client $1."
+  if [[ "$cur" = "$1" ]]; then 
+    logger "already prepared for client $1."
 
-    [ -n "$pid" ] && echo "server ready." && exit 0
+    [[ -n "$pid" ]] && echo 'server ready.' && exit 0
   else
     logger "preparing for client $1..."
 
     sed -i s/$cur/$1/g $file
 
-    if [ -n "$pid" ]; then
-      kill $pid || errorout "existing server wouldn't die."
+    if [[ -n "$pid" ]]; then
+      /etc/rc.d/synergys stop
     fi
   fi
 
-  synergys &>/dev/null && logger "server ready." || errorout "could not start server."
+  /etc/rc.d/synergys start
 
   exit 0
 }
 
-# each host will be tried in order
-HOSTS=('susan' 'howard' '192.168.0.12')
+# each host will be tried in order by ping
+hosts=('susan' 'howard')
 
 # keep a log
 log='/home/patrick/.logs/synergize.log'
@@ -63,21 +63,20 @@ log='/home/patrick/.logs/synergize.log'
 file='/etc/synergy.conf'
 
 # help message
-[ "$1" = "--help" ] && message 
+[[ "$1" =~ -h|--help ]] && message 
 
 # only root
-[ $(id -u) -ne 0 ] && errorout "only root can do that."
+[[ $(id -u) -ne 0 ]] && errorout 'only root can do that.'
 
 # need X
-[ -z "$DISPLAY" ] && errorout "no X display available."
+[[ -z "$DISPLAY" ]] && errorout 'no X display available.'
 
 # try $1 if passed
-[ -n "$1" ] && connect $1
+[[ -n "$1" ]] && connect $1
 
-# try default HOSTS
-for host in ${HOSTS[@]}; do
+# try default hosts
+for host in ${hosts[@]}; do
   ping -c 1 $host &>/dev/null && connect $host
 done
 
-# if we're here, we've failed
-errorout "${HOSTS[@]}: no hosts found."
+errorout 'no hosts answered'
