upload: major rewrite, much more flexible

diff --git a/upload b/upload
--- a/upload
+++ b/upload
@@ -2,14 +2,69 @@
 #
 # pbrisbin 2009
 #
-# update aur packages
+# Description:
+#
+# Somewhat automate the handling of aur packages where you control the
+# source files.
+#
+# How it works:
+#
+# Place a file in some known directory* for each package you manage, name
+# this file the name of the package.
+#
+# That file will be sourced by this script if that package is passed as
+# an argument. The sourcing should define one variable and two
+# functions:
+#
+#   package_files    : the path to the directory that will ultimately be
+#                      tarred and uploaded to the AUR.
+#
+#   pre_edit_hook()  : this function will be called before the PKGBUILD
+#                      is presented for editing. Some useful things it
+#                      might do are update source files and md5sums.
+#
+#   post_edit_hook() : this function will be called after the PKGBUILD
+#                      has been edited, but before the files are tarred
+#                      and uploaded. Some useful things it might do are
+#                      remove ./{pkg,src} files created during the
+#                      md5sum update or a test packaging run.
+#
+# When defining the functions, you can use display(), warn(), and
+# errorout() as needed. Your functions should return 1 for failure and 0
+# for success.
+#
+# At this time, you can assume that the pre and post hooks will be run
+# from within the same directory as the PKGBUILD.
+#
+# Most errors just result in ending the processing of this argument.
+# Commands that fail should report their own errors.
+#
+# *The "known directory" is defaulted in-script for my usage, it can be
+# changed at runtime using the -b or --build_files options
 #
 ###
 
-errorout() { echo "error: $*" >&2; exit 1; }
-message()  { echo 'upload [ --skip ] <package> ...'; exit 1; }
+# help message
+message()  { 
+  cat << EOF
+  usage: upload [ -k ] [ -b <dir> ] <package> ...
+    options:
+      -k, --keep                don't discard the taurball after uploading
+      -b, --build-files         source build files from <dir>
 
+EOF
+  
+  exit 1
+}
+
+# std output commands
+display()  { echo "$*";                      }
+warn()     { echo "warning: $*" >&2;         }
+errorout() { echo "error: $*"   >&2; exit 1; }
+
+# prompt with Y default
 prompt() {
+  echo
   read -p "$*? [Y/n] " a
 
   case "${a:-y}" in
@@ -19,55 +74,95 @@ prompt() {
   esac
 }
 
-process() {
-  local pack archive 
+process_pkg() {
+  local pkg="$1"
+  local taur="/tmp/$pkg.tar.gz"
 
-  pack="$1"
-  archive="./$pack.tar.gz"
+  # ensure no cross-over
+  unset -v source_files
+  unset -f pre_edit_hook
+  unset -f post_edit_hook
 
-  [[ -d "$packages/$pack" ]] || errorout "no package at $packages/$1"
+  # source for new values
+  . "$build_files/$pkg" || return 1
 
-  if ! $skip; then
-    pushd "$packages/$pack" &>/dev/null    || errorout 'unable to change directory'
-    cp -v "$bin/$pack" .                   || errorout 'unable to copy sources'
-    [[ -f ./PKGBUILD ]]                    || errorout 'pkbuild not found'
-    makepkg -g >> ./PKGBUILD               || errorout 'failed updating md5sums'
-    vim ./PKGBUILD                         || errorout 'error editing pkgbuild'
-    rm -rv ./src                           || errorout 'error removing sources'
-    popd &>/dev/null                       || errorout 'unable to change directory'
-    tar cvpzf "$archive" "$packages/$pack" || errorout 'failed to compress archive'
+  # validate build file
+  [[ -n "$source_files" ]] || return 1
+  type -p pre_edit_hook    || return 1
+  type -p post_edit_hook   || return 1
+
+  # hooks and editing
+  pushd "$source_files" >/dev/null || return 1
+  pre_edit_hook                    || return 1
+  ${EDITOR:-vi} ./PKGBUILD         || return 1
+  post_edit_hook                   || return 1
+  popd >/dev/null                  || return 1
+
+  # tar and upload
+  create_taurball "$source_files" "$taur" || return 1
+  upload_taurball "$taur"                 || return 1
+
+  return 0
+}
+
+create_taurball() {
+  local dir="$1" taur="$2"
+
+  # display contents for review
+  ls -l -a "$dir"
+
+  prompt "create taurball from $dir" || return 1
+  pushd "${dir%/*}" >/dev/null       || return 1
+  tar cvpzf "$taur" "./${dir##*/}"   || return 1
+
+  return 0
+}
+
+# feel free to edit this if you have some other preferred way of
+# uploading to the AUR
+upload_taurball() {
+  local taur="$1"
+
+  prompt "upload $taur" || return 1
+
+  # using aurploader with stored password
+  local aurpass="$HOME/.aurploader_pass"
+  [[ -f "$aurpass" ]] || errorout "$aurpass: file not found."
+  aurploader -r -l "$aurpass" "$taur" || return 1
+
+  # cleanup?
+  if $keep; then
+    display "$taur: left in place"
+  else
+    rm -v "$taur" || return 1
   fi
 
-  # prompt to upload
-  prompt "upload $archive" || exit 1
-  aurploader -r -l "$aurpass" "$archive" || errorout 'failed to upload archive'
-  rm "$archive"                          || errorout 'failed to remove archive'
+  return 0
 }
 
 parse_options() {
-  skip=false
+  # set defaults
   args=()
+  keep=false
+  build_files="$HOME/AUR/.build_files"
 
+  # getopts
   while [[ -n "$1" ]]; do
     case "$1" in
-      --skip) skip=true      ;;
-      -*)     message        ;;
-      *)      args+=( "$1" ) ;;
+      -b|--build-files) shift; build_files="$1" ;;
+      -k|--keep)        keep=true               ;;
+      --)               break                   ;;
+      -*)               message                 ;;
+      *)                args+=( "$1" )          ;;
     esac
     shift
   done
-
-  [[ "${#args[@]}" -eq 0 ]] && message
 }
-
-bin="$HOME/.bin"
-packages="$HOME/AUR"
-aurpass="$HOME/.aurploader_pass"
-
-[[ -f "$aurpass" ]] || errorout "no password at $aurpass"
 
 parse_options "$@"
 
-for pack in "${args[@]}"; do process "$pack"; done
-
-echo 'success!'
+for pkg in "${args[@]}"; do
+  if ! process_pkg "$pkg"; then
+    warn "$pkg: processing stopped"
+  fi
+done
