xdg-open: try $BROWSER for non-file arguments

diff --git a/xdg-open b/xdg-open
--- a/xdg-open
+++ b/xdg-open
@@ -9,9 +9,12 @@
 
 file="$1"
 
+[[ -z "$file" ]] && { echo 'argument required' >&2; exit 1; }
+
 if [[ ! -f "$file" ]]; then
-  echo "$file: file not found" >&2
-  exit 1
+  echo "$file is not a file, trying \$BROWSER" >&2
+  $BROWSER "$file" &>/dev/null &
+  exit 0
 fi
 
 if ! which xdg-mime &>/dev/null; then
